#!/usr/bin/env python
import re

if __name__ == '__main__':
    import sys
    args = sys.argv
    if len(args) > 0:
        with open(args[1]) as f:
            days = re.findall(
                    r'<tr>\s*?<td class="bold_label" style="border:1px black dotted" align="center">\w\w\w <br/> \d\d-\d\d-\d\d\d\d</td>.*?</tr>',
                f.read(), re.DOTALL)
            for i, day in enumerate(days):
                print day
                for i, time in enumerate(day.split('\n')[0:12]):
                    if 'Lecture' in time:
                        print i, time
