#!/usr/bin/env python
import re

if __name__ == '__main__':
    import sys
    args = sys.argv
    if len(args) > 0:
        with open(args[1]) as f:
            days = re.findall(
                r'<tr>.+?<td class="bold_label".+?</tr>',
                f.read(), re.DOTALL)
            for d in days: print d; print '~~~~~~~~~~~~~~~'
